accounts/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.accounts, name='signup'),
    path('login/',views.loginUser, name='login'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    TopicCreateView,
    TopicListView,
    TopicDetailView,
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView
)

app_name = 'forum'

urlpatterns = [
    path('', TopicListView.as_view(), name='forum-index'),
    path('topic/add/', TopicCreateView.as_view(), name='topic-add'),
    path('topic/<int:pk>/', TopicDetailView.as_view(), name='topic-detail'),

    path('topic/<int:pk>/newpost/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='StartPage'),
]

patalogIA/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('video/', include('video.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('predication/', include('predication.urls')),
    path('forum/', include('forum.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum/models.py
"""
Database models
"""

from django.db import models
from django.utils import timezone
from django.urls import reverse

class Topic(models.Model):
    """ Topics contain posts """

    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('topic-detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.title

class Post(models.Model):
    """ Posts can be found under its topic. """

    author = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=50, default='untitled')
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    """ Comments are replies to posts """

    author = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    body = models.TextField()

    def __str__(self):
        return self.body

forum/forms.py
from django import forms

from .models import Comment, Topic

class CreateTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'title', 'description'
        ]

class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'body', 'author', 'post'
        ]

forum/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import FormMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Topic, Post, Comment
from .forms import CreateCommentForm

# Topic views

class TopicListView(ListView):
    model = Topic
    template_name = 'forum/index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'topics'

class TopicDetailView(DetailView):
    model = Topic

    def get_context_data(self, **kwargs):
        context = super(TopicDetailView, self).get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(topic=self.kwargs.get('pk'))
        return context

class TopicCreateView(LoginRequiredMixin, CreateView):
    model = Topic
    fields = ['title', 'description']

    def form_valid(self, form):
        return super().form_valid(form)

# Post views

class PostDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = Post
    form_class = CreateCommentForm

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.kwargs.get('pk'))
        context['form'] = CreateCommentForm(initial={'post': self.object, 'author': self.request.user})

        return context

    def get_success_url(self):
        return reverse('post-detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(PostDetailView, self).form_valid(form)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.topic = Topic.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False    

# Static pages

def login(request):
    return render(request, 'forum/login.html')

def logout(request):
    return render(request, 'forum/logout.html')

forum/templates/forum/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Custom css -->
        <link rel="stylesheet" type="text/css" href="{% static 'forumStatic/css/global.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">

        <title>Forum</title>
    </head>
    <body>
        

        <div class="row vertical-align header">
                <div class="col-3 offset-1">
                    <a href ="{% url 'forum:forum-index' %}"><i class="fas fa-comments fa-3x home-btn"></i></a>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-1 offset-5 text-right align-self-center">
                       
                    </div>
                    <div class="col-1 text-right align-self-center">
                            
                            
                        </div>
                {% else %}
                    <div class="col-1 offset-5 text-right align-self-center">
                        <a href="{% url 'registration:login' %}"><h3>log in</h3></a>
                    </div>
                    <div class="col-1 text-right align-self-center">
                        <a href="{% url 'registration:signup' %}"><h3>register</h3></a>
                    </div>
                {% endif %}
            </div>
        <div class="container-fluid">
            {% block content %}{% endblock %}
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="{% static 'forumStatic/js/headings.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

    <footer>
        <script src="{% static 'forumStatic/js/theme.js' %}"></script>

        <script>
            function loadThemeCSS(theme){
                var fileref = document.createElement("link");
                fileref.rel = "stylesheet";
                fileref.type = "text/css";

                if(theme == "dark"){
                    fileref.href = "{% static 'forumStatic/css/dark-theme.css' %}";
                }else{
                    fileref.href = "{% static 'forumStatic/css/light-theme.css' %}";
                }

                document.getElementsByTagName("head")[0].appendChild(fileref);
            }
        </script>
        
        <div id="theme-wrapper">
            <p>Dark Mode</p>
            <input class="switch" type="checkbox" id="darkSwitch" />
            <label class="switch" for="switch" onclick="onThemeChange();">Toggle</label>
        </div>

    </footer>

</html>

forum/templates/forum/index.html
{% extends "forum/base.html" %}
{% block content %}

    <div class="col-2 offset-5 mt-5">
            <h1 style="width: 6ch;">topics</h1>
    </div>

    {% if user.is_superuser %}
        <div id="topic-add">
            <a href="{% url 'forum:topic-add' %}">
                <h3><i class="fas fa-plus"></i></h3>
            </a>
        </div>
    {% endif %}

    <div class="topics">
        {% for topic in topics %}
            <div class="row">
                <div class="col-2 offset-5 text-center">
                    <a href="{% url 'forum:topic-detail' topic.id %}"><h3 class="row topic_title">{{ topic.title }}</h3></a>
                    <p class="row">{{ topic.description }}</p>
                    <hr>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %} 

forum/templates/forum/post_confirm_delete.html
{% extends "forum/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'forum:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

forum/templates/forum/post_detail.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        <div class="col-4 offset-4 mt-5">
                <h1 id="header">{{ object.title }}</h1>
        </div>
    </div>

    <div class="row">
        
        {% if object.author == user %}
            <div class="col-4 offset-4">
                <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'forum:post-update' object.id %}">edit</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'forum:post-delete' object.id %}">delete</a>
            </div>
        {% endif %}
    </div>

    <div class="row mt-4">
        <div class="col-1 offset-4 ">
           
        </div>

        <div class="col-3 align-self-center">
            <h5>{{ object.body }}<h5>
        </div>
    </div>

    <div class="col-4 offset-4 mt-2">
        <hr class="mt-5">
    </div>

    {% for comment in comments %}
        <div class="row mt-4 mb-4">
            <div class="col-1 offset-4 ">
                
            </div>
            <div class="col-3 align-self-center">
                <h5>{{ comment.body }}<h5>
            </div>
        </div>
    {% endfor %}

    <div class="row mt-2">
        <div class="col-1 offset-4 ">
            <img class="rounded-circle account-img thumbpic" src="{{ user.profile.image.url }}" height="50">
        </div>

        <div class="col-3">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
    
    <script>
        document.getElementById("div_id_author").style.display="none"
        document.getElementById("div_id_post").style.display="none"
        document.getElementById("div_id_body").getElementsByTagName('label')[0].style.display="none"
    </script>
{% endblock content %} 

forum/templates/forum/post_form.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        <div class="col-2 offset-5 mt-5">
            <h1 style="width: 8ch;">new post</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-2 offset-5 mt-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Create</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %} 

forum/templates/forum/topic_detail.html
{% extends "forum/base.html" %}
{% block content %}

    <div class="col-4 offset-4 mt-5">
        <h1 id="header">{{ object.title }}</h1>
    </div>

    {% if request.user.is_authenticated %}
        <div class="col-4 offset-4">
            <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'forum:post-create' object.id %}">new post</a>
        </div>
    {% endif %}

    <div class="posts mt-5">
        {% for post in posts %}
            <div class="row post mb-4">
                <div class="col-4 offset-4 text-center">
                    <a href="{% url 'forum:post-detail' post.id %}">
                        <h3 class="post_title">{{ post.title }}</h3></a> <p> by {{ post.author }} </p>
                        <a href="{% url 'forum:profile' username=post.author.profile.user.username %}">
                            <img class="rounded-circle account-img thumbpic" src="{{ post.author.profile.image.url }}" height="25">
                        </a>
                    </a>
                    <hr>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %} 

forum/templates/forum/topic_form.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        <div class="col-2 offset-5 mt-5">
            <h1 style="width: 9ch;">new topic</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-2 offset-5 mt-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Create</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %} 