home/urls.py
from django.urls import path
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='StartPage'),
]

patalogIA/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('video/', include('video.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('predication/', include('predication.urls')),
    path('forum/', include('forum.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path, include
from . import views

app_name = 'questions'


urlpatterns = [
    path('',views.question, name='questiontype'),
    path('demarcate',views.createDemarcate, name='demarcatePage'),
    path('MCQs',views.MCQs, name='MCQsPage'),
    path('quiz',views.showQuestions, name='quiz'),
    path('quizdetail/<str:pk>', views.quizdetail, name='quizdetail'),
    path('demarcateQuiz', views.demarcateQuiz, name='demarcateQuiz'),
    path('demarcateQuizDetail/<str:pk>', views.demarcateQuizDetail, name = 'demarcateQuizDetail')

]

questions/models.py
from django.db import models
import uuid

# Demarcte Questions or MCQS!
class QuestionTypes(models.Model):
    idtype_questions = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    category = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        db_table = 'question_types'

    def __str__(self):
        return self.category

class Questions(models.Model):
    idquestions = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    question = models.IntegerField(db_column='questaoNum', blank=True, null=True)  # Field name made lowercase.z    
    description = models.CharField(max_length=150, blank=True, null=True)
    value = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    certain = models.CharField(max_length=1, blank=True, null=True, default="A")
    typequestionandidtypequestion = models.ForeignKey('QuestionTypes', models.DO_NOTHING, verbose_name="Type of Question", db_column='tipoquestoesidtipoquestoes', blank=True, null=True)
    questionnaireidquestionnaire = models.ForeignKey('Questionnaire', models.DO_NOTHING, verbose_name="Related Subject", db_column='questionarioidquestionario', blank=True, null=True)
    videoidvideo = models.ForeignKey('video.Video', models.DO_NOTHING, verbose_name="Link Video", db_column='videoidvideo', blank=True, null=True)
    codimage = models.ForeignKey('images.Image', models.DO_NOTHING, verbose_name="Link Image", db_column='codimagem', blank=True, null=True)

    class Meta:
        db_table = 'questions'
    
    def __str__(self):
        return self.description


class Questionnaire(models.Model):
    idquestionnaire = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=150, blank=True, null=True)
    Subject = models.CharField(max_length=250, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    quests = models.IntegerField(blank=True, null=True)
    #Co Educator This Feild needs to be addressed
    co_educator = models.ForeignKey('accounts.User', models.DO_NOTHING, db_column='codidusuario', blank=True, null=True)
    usercode = models.ForeignKey('accounts.UserType', models.DO_NOTHING, db_column='codtipousuario', blank=True, null=True)

    class Meta:
        db_table = 'questionnaire'
    def __str__(self):
        return self.Subject

#MCQS Option
class AlternativeQuestions(models.Model):
    idquestions_alternatives = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    description = models.CharField(max_length=250, blank=True, null=True)
    letter = models.CharField(max_length=1, blank=True, null=True)
    questoes_questoes_id = models.ForeignKey('Questions', models.DO_NOTHING, verbose_name="Related Question", db_column='questoes_idquestoes')

    class Meta:
        db_table = 'alternative_questions'
    def __str__(self):
        return self.description



class Result(models.Model):
    idresult = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    iduser_user = models.ForeignKey('accounts.User', models.DO_NOTHING, db_column='usuario_idusuario', blank=True, null=True)
    quiz_quiz_id = models.ForeignKey('Questionnaire', models.DO_NOTHING, db_column='questionario_idquestionario', blank=True, null=True)
    descriptiondate = models.DateTimeField(blank=True, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'result'


# Temp
class Cases(models.Model):
    idcase = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    descricao = models.CharField(max_length=250, blank=True, null=True)
    imageidimage = models.ForeignKey('images.Image', models.DO_NOTHING, db_column='imagemidimagem', blank=True, null=True)
    # This Needs to be Discussed
    this_question = models.ForeignKey('Questions', models.DO_NOTHING, db_column='questoesidquestao')
    useriduser = models.ForeignKey('accounts.User', models.DO_NOTHING, db_column='usuarioidusuario', blank=True, null=True)

    class Meta:
        db_table = 'cases'

questions/forms.py
from images.models import Image
from video.models import Video
from .models import QuestionTypes,Questions,Questionnaire
from django import forms
from demarcate.models import demarcateQuestion




class QuestionTypeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=QuestionTypes.objects.all(), to_field_name="category", empty_label="Select Category", label='')
    category.widget.attrs.update({'class': 'form-select', 'placeholder': 'category'})
    class Meta:
        model = QuestionTypes
        fields = '__all__'


class CreateQuestionsForm(forms.ModelForm):
    question = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Question'}), label='')
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}), label='')
    value = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Value'}), label='')
    certain = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Certain'}), label='')
    questionnaireidquestionnaire = forms.ModelChoiceField(
        queryset=Questionnaire.objects.all(),
        label="",
        empty_label="Select questionnaireidquestionnaire"
    )
    questionnaireidquestionnaire.widget.attrs.update({'class': 'form-select', 'placeholder': 'Video Link'})
    videoidvideo = forms.ModelChoiceField(
        queryset=Video.objects.all(),
        label="",
        empty_label="Select videoidvideo"
    )
    videoidvideo.widget.attrs.update({'class': 'form-select', 'placeholder': 'Video Link'})
    codimage = forms.ModelChoiceField(
        queryset=Image.objects.all(),
        label="",
        empty_label="Select codimage"
    )
    codimage.widget.attrs.update({'class': 'form-select', 'placeholder': 'Video Link'})
    class Meta:
        model = Questions
        fields = '__all__'
        exclude = ['typequestionandidtypequestion']
        

class CreateQuestionnaireForm(forms.ModelForm):
    class Meta:
        model = Questionnaire
        fields = '__all__'


class createImageQuestion(forms.Form):
    question = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Question'}), label='')
    question_image = forms.CharField(widget=forms.FileInput(attrs={'class': 'form-control', 'placeholder': 'question', 'name':"question_image", 'accept':"image/*", 'id':'id_questionImage'}), label='Question image:')
    class Meta:
        model = demarcateQuestion 
        fields = '__all__'
        exclude = ('x','y','w','h','area')

questions/views.py
from django.shortcuts import render, redirect
from .forms import QuestionTypeForm,CreateQuestionsForm,CreateQuestionnaireForm, createImageQuestion
from .models import Questions, Questionnaire, AlternativeQuestions
from demarcate.models import demarcate,demarcateQuestion
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import math


def question(request):
    form = QuestionTypeForm(request.POST or None)
    if form.is_valid():
        if str(form.cleaned_data.get('category')) == 'Demarcate':
            return redirect('questions:demarcatePage')
        elif str(form.cleaned_data.get('category')) == 'Multiple Choice Questions':
            return redirect('questions:MCQsPage')
    context = {'form':form}
    return render(request, 'questions/teacher/questionType.html', context)\

"""-------------------------------------------------------------------------------------------------------"""
"""Demarcate Question and Answer Section"""
@csrf_exempt
def createDemarcate(request):
    """Process images uploaded by users"""
    form = createImageQuestion(request.POST or None)
    if request.method == "POST":
        form = createImageQuestion(request.POST,request.FILES)
        instance = form.save(commit=False)
        x1 = int(request.POST.get("x1"))
        y1 = int(request.POST.get("y1"))
        x2 = int(request.POST.get("x2"))
        y2 = int(request.POST.get("y2"))
        getArea = findarea(x1,x2,y1,y2)
        #createPoints  = demarcateQuestion(x = x1, y = y1, w = (x2 - x1), h = (y2 - y1), area = getArea, idimage = instance)
        instance.x = x1
        instance.y = y1
        instance.w = (x2 - x1)
        instance.h = (y2 - y1)
        instance.area = getArea
        instance.save()
        #createPoints.save()
    return render(request, 'questions/teacher/demarcatePage.html', {'form':form})

def findarea(x1,x2,y1,y2):
    wSqrOfX =  (x2-x1) ** 2
    wSqrOfY = (y2-y1) ** 2
    sumOfSquares = wSqrOfX + wSqrOfY
    area = math.sqrt(sumOfSquares)
    return int(area)

def demarcateQuiz(request):
    getQuestions = demarcateQuestion.objects.all()
    context = {'AllQuestions':getQuestions}
    return render(request,'questions/student/demarcatequestions.html', context)

def demarcateQuizDetail(request,pk):
    getDetail = demarcateQuestion.objects.get(idmarks = pk)
    context = {'question':getDetail}

    if request.method == "POST":
        x1 = int(request.POST.get("x1"))
        y1 = int(request.POST.get("y1"))
        x2 = int(request.POST.get("x2"))
        y2 = int(request.POST.get("y2"))
        getArea = findarea(x1,x2,y1,y2)
        w = (x2 - x1)
        h = (y2 - y1)

        threshold = 30
        
        x_range = range((getDetail.x-threshold),(getDetail.x+threshold),1)
        y_range = range((getDetail.y-threshold),(getDetail.y+threshold),1)
        w_range = range((getDetail.w-threshold),(getDetail.w+threshold),1)
        h_range = range((getDetail.h-threshold),(getDetail.h+threshold),1)
        area_range = range((getDetail.area-threshold),(getDetail.area+threshold),1)

        print(getDetail.x - x1)
        print(getDetail.y - y1)
        print(getDetail.area - getArea)
        print(getDetail.w - w)
        print(getDetail.h - h)
        if (x1 in x_range) and (y1 in y_range) and (w in w_range) and (h in h_range) and (getArea in area_range):
            print("Answer is Correct")
        else:
            print("Ansewr is Wrong")

    return render(request, 'questions/student/demarcatequestiondetail.html', context)

"""-------------------------------------------------------------------------------------------------------"""

def MCQs(request):
    form = CreateQuestionsForm(request.POST or None)
    if form.is_valid():
        print('MCQ Created')
        form.save()
    context = {'form':form}
    return render(request, 'questions/teacher/MCQsPage.html', context)

def showQuestions(request):
    descQuesiton = Questions.objects.all()
    context = {'QuestionText':descQuesiton}
    return render(request, 'questions/student/quiz.html', context)

def quizdetail(request, pk):
    getOptions = AlternativeQuestions.objects.filter(questoes_questoes_id__description = pk)
    rightAns = Questions.objects.get(description = pk)
    getQuestion = pk
    context = {'Question':getQuestion,'Options': getOptions}

    if request.method == "POST":
        selectedOptionA = request.POST.get('A')
        selectedOptionB = request.POST.get('B')
        selectedOptionC = request.POST.get('C')
        selectedOptionD = request.POST.get('D')

        if selectedOptionA == rightAns.certain:
            print('A Your Answer is correct')
            return HttpResponse('Your Answer is Correct')
        elif selectedOptionB == rightAns.certain:
            print('B Your Answer is correct')
            return HttpResponse('Your Answer is Correct')
        elif selectedOptionC == rightAns.certain:
            print('C Your Answer is correct')
            return HttpResponse('Your Answer is Correct')
        elif selectedOptionD == rightAns.certain:
            print('D Your Answer is correct')
            return HttpResponse('Your Answer is Correct')

    return render(request, 'questions/student/questionwithoptions.html', context)

questions/templates/questions/student/demarcatequestiondetail.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Demarcate question details CSS -->
    <link href="{% static 'assets/css/DemarcatequestionsCSS.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <title>Document</title>
</head>
<body>
    <section id="appointment" class="appointment section-bg">
    <div class="container">
            <div class="text-center">
        <div class="section-title">
        <h2>MCQs</h2>
        </div>
        <canvas style="background: url('{{question.questionImage.url}}');" id="canvas" width="800" height="500"></canvas>
        <p>
        <label for="id_questionImage">Question image:</label>
        <!-- <input type="file" name="question_image" accept="image/*" id="id_question_image"> -->
        <output id="list"></output></p>
    <form action="" method="post" class="php-email-form" enctype="multipart/form-data" id="QuestionForm">
            {% csrf_token %}
        <div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-8">
    <div class="row align-items-center g-3 p-3">
        <div class="col-3">
            X1:<input class="form-control" type="text" name="x1" id="x1" value="0">
        </div>
        <div class="col-3">
            Y1:<input class="form-control" type="text" name="y1" id="y1" value="0">
        </div>
        <div class="col-3">
            X2:<input class="form-control" type="text" name="x2" id="x2" value="0">
            </div>
        <div class="col-3">
            Y2:<input class="form-control" type="text" name="y2" id="y2" value="0">
        </div>
    </div>
        </div>
      </div>
            </div>
            <button type="submit" name="submitbtn">Submit</button>
    </form>
            </div>
    <script>
        // Creating the demarcation tool

        //var canvas = document.getElementById("canvas"),ctx = canvas.getContext("2d");

        var canvas=document.getElementById('canvas'),ctx= canvas.getContext('2d');

        //Variables
        var canvasx = $(canvas).offset().left;
        var canvasy = $(canvas).offset().top;
        var last_mousex = last_mousey = 0;
        var mousex = mousey = 0;
        var mousedown = false;
        var x1 = 0, x2 = 0, y1 = 0, y2 = 0;
        //Mousemove
        $(canvas).on('mousemove', function (e) {
            mousex = parseInt(e.clientX - canvasx);
            mousey = parseInt(e.clientY - canvasy);
            if (mousedown) {
                ctx.clearRect(0, 0, canvas.width, canvas.height); //clear canvas
                ctx.beginPath();
                var width = mousex - last_mousex;
                var height = mousey - last_mousey;
                ctx.rect(last_mousex, last_mousey, width, height);
                ctx.strokeStyle = 'blue';
                ctx.lineWidth = 5;
                ctx.stroke();
            }
            //Output
            x2 = e.clientX;
            y2 = e.clientY;
        });
        //Mousedown
        $(canvas).on('mousedown', function (e) {
            last_mousex = parseInt(e.clientX - canvasx);
            last_mousey = parseInt(e.clientY - canvasy);
            mousedown = true;
            x1 = e.clientX;
            y1 = e.clientY;
        });
        //Mouseup
        $(canvas).on('mouseup', function (e) {
            mousedown = false;
            //for testing
            document.getElementById("x1").value = x1;
            document.getElementById("y1").value = y1;
            document.getElementById("x2").value = x2;
            document.getElementById("y2").value = y2;

        });
    </script>
    </div>
            </div>

    </section>
</body>
</html>
{% endblock content %}

questions/templates/questions/student/demarcatequestions.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demarcate Quiz</title>
</head>
<body>
<section id="appointment" class="appointment section-bg">
    <div class="container">
        <div class="section-title">
        <h2>Questions</h2>
        </div>
  <div class="container">
  <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">
      <ul class="list-group mb-3">
          {% for question in AllQuestions %}
        <a style="margin: 10px 0;font-size:28px;text-align:center" href="{% url 'questions:demarcateQuizDetail' question.idmarks %}" class="btn btn-outline-primary">
            {{question.question}}
        </a>
          {% endfor %}
      </ul>
    </div>
  </div>
</div>
    </div>
</section>
</body>
</html>
{% endblock content %}

questions/templates/questions/student/questionwithoptions.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- RadioInputs CSS -->
    <link href="{% static 'assets/css/radiobuttonsCSS.css' %}" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

    <title>Question With Detial</title>
</head>
<body>
<section id="appointment" class="appointment section-bg">
    <div class="container">
    <div class="section-title">
        <h2>{{Question}}</h2>
        </div>
    <form action="" method="post" class="php-email-form">
        {% csrf_token %}
        {% for option in Options %}
    <div class="row mb-3">
    <div class="custom-choose mb-3">
     <input type="radio" id="{{option.letter}}" value="{{option.letter}}" name="option">
     <label for="{{option.letter}}">{{option}}</label>
    </div>
    </div>
        {% endfor %}
        <div class="text-center">
<button class="appointment-btn" type="submit" value="Save">Submit</button>
        </div>
</form>

  </div>
</section>
</body>
</html>
{% endblock content %}

questions/templates/questions/student/quiz.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Page For Student</title>
</head>
<body>
<section id="appointment" class="appointment section-bg">
    <div class="container">
    <div class="section-title">
        <h2>Question Page For Student</h2>
    </div>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">
      <ul class="list-group mb-3">
          {% for Question in QuestionText %}
        <a style="text-align:center;margin: 10px 0;" href="{% url 'questions:quizdetail' Question.description %}" class="btn btn-outline-primary">
            <h5 style="margin-top: 8px;">Question : {{Question.question}}</h5>
        </a>
          {% endfor %}
      </ul>
    </div>
  </div>
</div>
        </div>
</section>
<!-- End Appointment Section -->
</body>
<style>

</style>
</html>

{% endblock content %}